server:
  port: 8181
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tele?currentSchema=chat
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    hikari:
      connectionTimeout: 30000
      idleTimeout: 60000
      maxLifetime: 7190000
      minimumIdle: 2
      maximumPoolSize: 50
    tomcat:
      min-idle: 2
      max-idle: 2
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    webchat.demo: info

chat:
  history:
    count: 11