version: '3.7'
services:
  chat-db:
    image: postgres:13.2
    environment:
      PGDATA: "/var/lib/postgresql/data/"
      POSTGRES_DB: tele
    volumes:
      - chat-postgres:/var/lib/postgresql/data:rw
    restart: always
    ports:
      - 5432:5432

volumes:
  chat-postgres: