version: '3.7'
services:
  chat-db:
    image: postgres:13.2
    environment:
      PGDATA: "/var/lib/postgresql/data/"
      POSTGRES_DB: "tele"
      POSTGRES_PASSWORD: "password"
    volumes:
      - chat-postgres:/var/lib/postgresql/data:rw
    restart: always
    ports:
      - 5432:5432
    networks:
    - vla_network
  chat-jav:
    image: webchat
    restart: always
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://chat-db:5432/tele?currentSchema=chat"
    ports:
      - 8181:8181
    depends_on:
     - chat-db
    networks:
    - vla_network
networks:
  vla_network:
    driver: bridge
volumes:
  chat-postgres:
